# dup.out: 6-1testdup.cpp
# 	gcc 6-1testdup.cpp -o dup.out

writev.out: 6-2testwritev.cpp
	g++ 6-2testwritev.cpp -o writev.out

sendfile.out: 6-3testsendfile.cpp
	gcc 6-3testsendfile.cpp -o sendfile.out

clean:
	rm *.out